### ISSUE TITLE
Help with multiple packages example

### ISSUE THREAD

**Issue by timhughes** [pantsbuild/example-python#15]
In the process of assessing Pants suitability to pull a bunch of pre-existing packages together, I am attempting to create an example multi-package pants project https://github.com/timhughes/pants-example-python-multiple-packages based on this project.

I can get it to build dist/project1.pex and dist/project2.pex but then when I run them I get import errors like 
```
ImportError: Error while finding module specification for 'project1.main1' (ModuleNotFoundError: No module named 'project1')
```
Same issue with the all the tests, I am getting import errors which can be seen at https://github.com/timhughes/pants-example-python-multiple-packages/runs/676529298?check_suite_focus=true  

If I can get this to work it may be another useful example of a more complicated setup than this project that you could use.

**Comment by benjyw** [comment]
Thanks for the report, looking into it now!

**Comment by benjyw** [comment]
This looks like an issue with your source_roots. Based on the structure of your code, it looks like you want them to be:

```
root_patterns = [
    "src/python/library1/src",
    "src/python/project1/src",
    "src/python/project2/src",
]
```
(and similar for tests)

To clarify, the source_roots are the roots of the import namespace. Your entry_point is `project1.cli`, which maps to `project1/cli.py`, so the source root must be the parent of that path, namely `src/python/project1/src/` (or `^/src/python/project1/src/` if you want to anchor the source_root at the repo root rather than allowing it as a suffix anywhere in the repo).

But note that then you will need to put the library's BUILD file under the source root. So you'll need two BUILD files, one for the source and one for the tests, because under your current layout those should be separate source roots. You could put the tests under `src/` if you want to of course.

Does that make sense? Sounds like we need to clarify the documentation a bit.

**Comment by timhughes** [comment]
That made enough sense for me to get it to work :-) Thanks. 

I have added a setup-py example project into my repo and updated to docs to be similar to this project.
