### ISSUE TITLE
Why put source in src/python ? 

### ISSUE THREAD

**Issue by RemiTorracinta** [pantsbuild/example-python#3]
We used that convention at my company, and then ultimately regretted that and put our base python package at the repo root.

Here was the reasoning:

- The src/python/tests/python convention came from some legacy system (Maven, I think?) and doesn't actually need to be followed to use pants. ([convo on the pants slack](https://pantsbuild.slack.com/archives/C046T6T9U/p1554497561060600))
- They're annoying to constantly type everywhere.
- Other systems don't have the same concept of different "source roots", which makes it difficult to use them in the repo (e.g., other build systems like bazel or plz.build, or things as simple as being able to run python or pytest without having to cd to a directory).

**Comment by benjyw** [comment]
Thanks for the comments! 

To clarify my reasoning:
- Pants doesn't require separate src/ and test/ roots, those are indeed a maven concept. In this repo you can see tests alongside non-test sources in the same dir. 
- You shouldn't need to cd to a directory to work with code under a source root. You just run commands against the relative path of the code you want to operate on.
- The idea of source roots isn't so much a build system concept as a codebase organization concept. The build tool can support flexible source roots or not (Pants does, and I'm pretty sure Bazel does, at least for JVM, maybe not for Python?). 

This example uses `src/python` only because I was imagining the example of a heterogeneous monorepo that has multiple languages, and this would be an example of the python slice of that. 

But if it's confusing I can certainly change this example to have the python source root be the root of the repo.

**Comment by Eric-Arellano** [comment]
> But if it's confusing I can certainly change this example to have the python source root be the root of the repo.

I think this would be a good change, and instead we add an additional `multiple languages` example repo to show you can have multiple source roots.

The idea of this example repo is to be the simplest possible configuration to show off Python support. We don't want to suggest to users that they must migrate their repo to using `src/python`.

**Comment by benjyw** [comment]
Fixed in https://github.com/pantsbuild/example-python/pull/4

@RemiTorracinta is this more useful?

**Comment by RemiTorracinta** [comment]
yes looks great!

**Comment by benjyw** [comment]
Closed in #4. Thanks for the feedback @RemiTorracinta !
